Update discord_integration.py
TwitchIO/TwitchIO pull request #131
Opened 2021-01-03 00:14 UTC by NekoTony

* **Please check if the PR fulfills these requirements**
- [Y ] Tests have been conducted on the PR
- [ N] Docs have been added / updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
A fix for the discord_integration.py file so it works.

* **What is the current behavior?** (You can also link to an open issue here)
Discord_integration.py is out of date

* **What is the new behavior (if this is a feature change)?**
Discord_integration.py is now fixed to work with latest version of d.py

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

2021-01-03 00:27 UTC, IAmTomahawkx commented
youve included your credentials in this pull request. I would suggest [deauthorizing](https://dev.twitch.tv/docs/authentication#revoking-access-tokens) that token

2021-01-03 00:34 UTC, NekoTony commented
Fixed and it's revoked, thanks.

2021-01-03 00:34 UTC, IAmTomahawkx requested changes

2021-01-03 00:34 UTC, IAmTomahawkx commented on examples/discord_integration.py
> +            initial_channels=['#ArthritisAC']
`initial_channels=['...']`

2021-01-03 00:34 UTC, IAmTomahawkx commented on examples/discord_integration.py
> +            nick='ArthritisAC',
`nick=''`

2021-01-03 00:34 UTC, IAmTomahawkx commented on examples/discord_integration.py
> +import discord
redundant import

2021-09-21 22:29 UTC, IAmTomahawkx commented
outdated

2021-09-21 22:29 UTC, closed without merging