Fix for channel point rewards in pubsub
TwitchIO/TwitchIO pull request #167
Opened 2021-05-17 23:04 UTC by izzy

* **Please check if the PR fulfills these requirements**
- [x] Tests have been conducted on the PR
- [ ] Docs have been added / updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bugfix for PubSub not being able to process Channel Point Reward messages

* **What is the current behavior?** (You can also link to an open issue here)
bot will err out on a KeyError, has problems parsing the date and does expect different fields than returned from the API

```
  File "...\src\twitchio\twitchio\ext\pubsub\models.py", line 132, in __init__
    self.timestamp = datetime.datetime.strptime(data["redemption"]["redeemed_at"], "%Y-%m-%dT%H:%M:%SZ")
KeyError: 'redemption'
```

* **What is the new behavior (if this is a feature change)?**
n/a

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
n/a

2021-05-17 23:09 UTC, IAmTomahawkx requested changes

2021-05-17 23:09 UTC, IAmTomahawkx commented on twitchio/ext/pubsub/models.py
> +        if "user_input" in redemption:
`redemption.get("user_input")`

2021-05-27 02:25 UTC, charlesmadere commented
Can't wait for this to be merged 😯 it will make my bot so much better. Thank you @izzy for your work!

2021-05-27 02:29 UTC, IAmTomahawkx approved these changes

2021-05-27 02:29 UTC, merged