Fix EventSub
TwitchIO/TwitchIO pull request #176
Opened 2021-06-28 01:23 UTC by mitsuaky

* **Please check if the PR fulfills these requirements**
- [x] Tests have been conducted on the PR
- [ ] Docs have been added / updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Mainly fixing EventSubs

* **What is the current behavior?** (You can also link to an open issue here)
1. `ext.eventsubs.http` is using the wrong paths to eventsub.
2. `ext.eventsubs.models` have incorrect strptime formating.
3. All the on_event for eventsub events is broken.
4. `Client.from_client_credentials()` not working.

* **What is the new behavior (if this is a feature change)?**
1. Fixed all the issues mentioned above.
2. Added a `_raw_data` on `ext.eventsub.models.Subscription`.
3. Added a debug message to `http._request()`.
4. Fixed KeyError when using `http.validate()` from a Client created with `Client.from_client_credentials()`.
5. `ext.eventsubs.http.delete_subscription()` now accepts `ext.eventsub.models.Subscription` too.
6. `http.get_extension_analytics()` and `http.get_game_analytics()` now raises `NotImplementedError` instead of just passing.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No.

2021-06-28 01:28 UTC, IAmTomahawkx requested changes

2021-06-28 01:28 UTC, IAmTomahawkx commented on twitchio/client.py
> +            This is not suitable for logging in to IRC.
Not relevant to the pr

2021-06-28 01:28 UTC, IAmTomahawkx commented on twitchio/client.py
> +            client=self, loop=self.loop, initial_channels=None, heartbeat=None
Not relevant to the pr

2021-06-28 01:28 UTC, IAmTomahawkx commented on twitchio/client.py
> +        for chunk in [ids[x: x + 3] for x in range(0, len(ids), 3)]:
Not relevant to the pr

2021-06-28 01:28 UTC, IAmTomahawkx commented on twitchio/ext/eventsub/http.py
> +    from .models import Subscription
Add this to the import directly above?

2021-06-28 01:28 UTC, IAmTomahawkx commented on twitchio/ext/eventsub/models.py
> +        self._raw_data = data
Storing raw data is counter intuitive, the models should cover all data anyways

2021-06-28 01:33 UTC, mitsuaky commented on twitchio/client.py
> +            client=self, loop=self.loop, initial_channels=None, heartbeat=None
It fixes the from_client_credentials()

2021-06-28 03:21 UTC, IAmTomahawkx commented on twitchio/client.py
> +            client=self, loop=self.loop, initial_channels=None, heartbeat=None
This is a separate PR

2021-06-29 00:29 UTC, IAmTomahawkx approved these changes

2021-06-29 00:31 UTC, merged