Additional methods + fix remove_cog
TwitchIO/TwitchIO pull request #195
Opened 2021-08-05 12:39 UTC by chillymosh

Added fetch_follow to client method to compare any 2 users relationship (from 1.2.3 missing from 2.0)
Can use ID or name

Added fetch_channel to client
You can now fetch the data for any channel without using private _http private methods using ID or name

I have a fix for remove_cog in my PR which now makes it work when called directly or through unload_module.
It worked fine if you call it directly e.g. self.remove_cog('Cogname') but when you try and unload a module it failed since it was a string and not a cog object. Adding a try: except: resolves it.

Tided up some general code

2021-08-06 23:01 UTC, IAmTomahawkx reviewed
I'm not sure if you've used the proper formatting on this, we use black with a *120* line length

2021-08-06 23:01 UTC, IAmTomahawkx commented on twitchio/parse.py
> +    elif groups[2] in ["PRIVMSG", "PRIVMSG(ECHO)"]:
Maybe a set here

2021-08-07 18:27 UTC, chillymosh commented on twitchio/parse.py
> +    elif groups[2] in ["PRIVMSG", "PRIVMSG(ECHO)"]:
Changed to set

2021-08-07 18:29 UTC, chillymosh commented on twitchio/client.py
> +        return await self._http.get_channels(broadcaster)
Created a new model called ChannelInfo and this now returns that

<ChannelInfo user=<PartialUser id=21734222, name=chillymosh> game_id=26936 game_name=Music title=Testing New  language=en delay=0>

2021-08-07 18:31 UTC, chillymosh commented on twitchio/client.py
Moved this to user.py from client and is access as PartialUser.fetch_follow(PartialUser)  can use to_user kwarg and token= kwag
returns
<FollowEvent from_user=<PartialUser id=21734222, name=chillymosh> to_user=<PartialUser id=247716086, name=McRocklin> followed_at=2020-09-10 21:05:59>

2021-08-07 18:38 UTC, chillymosh commented
Changed my black line settings to 120, I had missed that setting on the workspace I was using.

2021-08-07 21:34 UTC, chillymosh commented on twitchio/ext/commands/bot.py
> +            cog = self._cogs.pop(cog_name)
I'm digging deeper into this one as there is something else at play here

2021-08-10 00:42 UTC, IAmTomahawkx requested changes

2021-08-10 00:42 UTC, IAmTomahawkx commented on twitchio/user.py
> +    async def fetch_follow(self, to_user, token: str = None):
to_user isnt typed

2021-08-10 07:10 UTC, chillymosh commented on twitchio/user.py
> +    async def fetch_follow(self, to_user, token: str = None):
This is now type hinted in latest push

2021-08-11 08:21 UTC, chillymosh commented
Changes have been made

2021-08-12 02:02 UTC, IAmTomahawkx approved these changes

2021-08-12 02:02 UTC, merged