Add support for creating, getting, and resolving predictions
TwitchIO/TwitchIO pull request #207
Opened 2021-09-04 02:47 UTC by raechelmaelstrom

Resolves #178

2021-09-04 02:47 UTC, raechelmaelstrom commented
This doesn't have all the fields of the prediction data structure, but just wanting to check myself before I go any further.  Works with my test client to create, get and resolve predictions.

2021-09-04 04:14 UTC, IAmTomahawkx requested changes

2021-09-04 04:14 UTC, IAmTomahawkx commented on twitchio/models.py
> +        self.created_at: str = data["created_at"]
These should be converted to datetime objects.

2021-09-04 04:14 UTC, IAmTomahawkx commented on twitchio/models.py
> +        self.color: str = data["color"]
Alias colour to color

2021-09-04 04:14 UTC, IAmTomahawkx commented on twitchio/user.py
> +    async def end_prediction(self, token: str, prediction_id: str, status: str, winning_outcome_id: str = None):
Missing return type

2021-09-04 04:14 UTC, IAmTomahawkx commented on twitchio/user.py
> +    async def get_predictions(self, token: str, prediction_id: str = None):
Missing return type

2021-09-04 04:14 UTC, IAmTomahawkx commented on twitchio/user.py
> +    async def create_prediction(self, token: str, title: str, blue_outcome: str, pink_outcome: str, prediction_window: int):
Missing return type

2021-09-04 04:14 UTC, IAmTomahawkx commented on twitchio/user.py
> +        outcomes: :class:`List[str]`
Docstring doesn't match signature

2021-09-04 04:14 UTC, IAmTomahawkx commented on twitchio/http.py
> +        logging.debug(f"Sending prediction {body}")
(Doing) logging here isn't consistent with the rest of the library

2021-09-04 04:14 UTC, IAmTomahawkx commented
Thanks for the pr, just a couple things that need changing

2021-09-07 01:23 UTC, raechelmaelstrom commented
Okay this one is ready for another look!  I had some trouble with the date time stuff because apparently twitch is giving me dates of the format: 2021-09-07T01:21:27.725465223Z which python did not like.  Seems like different parts of the API all have different time stamp formats though.

2021-09-07 05:23 UTC, IAmTomahawkx commented
The api is very inconsistent. I'm pretty sure they try to be as inconsistent as possible tbh. I'll review this again in a few hours, thanks

2021-09-07 07:30 UTC, IAmTomahawkx approved these changes

2021-09-07 07:32 UTC, merged