Added model for channel subscription event to models.py in twitchio\e…
TwitchIO/TwitchIO pull request #264
Opened 2022-02-08 22:13 UTC by splaudpanther

…xt\pubsub

## Added model for Twitch Channel Subscription PubSub Event

The docs for version latest indicated that the model had not yet been implemented for this particular pubsub event, it was stated that a PR could be submitted, this is my attempt at implementing said model

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
    - [ ] I have updated the changelog with a quick recap of my changes.
- [ ] This PR fixes an issue.
- [X ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-02-08 22:20 UTC, IAmTomahawkx requested changes
please add your changes to docs/changelog.rst
other than that, LGTM

2022-02-08 22:20 UTC, IAmTomahawkx commented on twitchio/ext/pubsub/models.py
> +        self.recipient_id: int = (int(subscription["recipient_id"]) if self.is_gift is True else None)
dont actually need the outer () here

2022-02-08 22:28 UTC, chillymosh commented on twitchio/ext/pubsub/models.py
> +    message: :class:`PubSubChatMessage`
this should be a str

2022-02-08 22:28 UTC, chillymosh commented on twitchio/ext/pubsub/models.py
> +        ID of the channel that has been subscribed or subgifted.
Should be a single channel attribute which is a twitchio.Channel obeject

2022-02-08 22:29 UTC, chillymosh commented on twitchio/ext/pubsub/models.py
> +        Login name of the subscription gift recipient
Should be twitchio.PartialUser

2022-02-09 08:17 UTC, chillymosh requested changes

2022-02-09 08:17 UTC, chillymosh commented on twitchio/ext/pubsub/models.py
> +from re import sub
Why has re.sub been imported?

2022-02-09 08:17 UTC, chillymosh commented on twitchio/ext/pubsub/models.py
> +    channel_id: :class:`int`
This is not needed if you have a channel object

2022-02-09 08:17 UTC, chillymosh commented on twitchio/ext/pubsub/models.py
> +        self.message = PubSubChatMessage(subscription["sub_message"]["message"],  subscription["sub_message"]["emotes"] if subscription["sub_message"]["emotes"] is not None else None)
I think emoji would be better as its own attribute, remember it returns a List of dicts

2022-02-09 08:17 UTC, chillymosh commented on twitchio/ext/pubsub/models.py
> +        self.recipient = PartialUser(client._http, subscription["recipient_user_name"], int(subscription["recipient_id"]), subscription["recipient_display_name"]) if self.is_gift is True else None
PartialUser does not take display_name

2022-02-09 08:17 UTC, chillymosh commented on twitchio/ext/pubsub/models.py
> +        self.user = PartialUser(client._http, subscription["user_id"], subscription["user_name"], subscription["display_name"]) if self.context != "anongiftsub" or self.context != "anonresubgift" els
It would probably be better to check if self.context not in set { } 
Also PartialUser does not take display_name

2022-02-14 15:53 UTC, merged