Add support for type and user_id queries on get_subscriptions
TwitchIO/TwitchIO pull request #381
Opened 2023-01-13 04:45 UTC by PredaaA

This PR adds support for `type` and `user_id` queries to EventSub get_subscriptions.
https://dev.twitch.tv/docs/api/reference/#get-eventsub-subscriptions

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
    - [x] I have updated the changelog with a quick recap of my changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-01-13 08:24 UTC, chillymosh commented
Just to note, the filters are mutually exclusive so if more than one are sent it will probably fail with a 400 error.

The typings should probably be `Optional` since they are set to None and are also not required.

I'll let @IAmTomahawkx confirm this as he worked on Eventsub.

2023-01-13 09:16 UTC, IAmTomahawkx requested changes
You'll need to ensure that only one of these is passed as chilly mentioned, probably best to do it at the http level. Other than that just some typing nitpicks (a lot of the lib is typed like this, unfortunately how I did it is actually wrong)

2023-01-13 09:16 UTC, IAmTomahawkx commented on twitchio/ext/eventsub/server.py
> +    async def get_subscriptions(self, status: str = None, sub_type: str = None, user_id: str = None):
both of these are Optional, user_id should be Optional[int] at a user facing level to remain consistent with the rest of the lib. status should technically also be Optional[str] to actually pass type checking.

2023-01-13 09:16 UTC, IAmTomahawkx commented on twitchio/ext/eventsub/server.py
> +    async def get_subscriptions(self, status: str = None, sub_type: str = None, user_id: str = None):
don't forget to cast back to `str` on the user_id in the underlying method

2023-01-13 23:55 UTC, PredaaA commented
Just pushed requested changes.

2023-01-14 01:54 UTC, IAmTomahawkx approved these changes
LGTM

2023-03-19 02:19 UTC, IAmTomahawkx commented
@PredaaA can you fix the merge conflicts so i can merge this? thanks!

2023-03-19 03:54 UTC, PredaaA commented
Yup, done!

2023-03-19 04:10 UTC, merged