Cleanly teardown websocket
TwitchIO/TwitchIO pull request #93
Opened 2020-02-20 16:34 UTC by enykeev

* **Please check if the PR fulfills these requirements**
- [x] Tests have been conducted on the PR
- [ ] Docs have been added / updated

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix

* **What is the current behavior?** (You can also link to an open issue here)

On KeyboardInterrupt, bot closes websocket connection without awaiting the results resulting in warning:
```
RuntimeWarning: coroutine 'WebSocketCommonProtocol.close' was never awaited
  self._websocket.close()
```

* **What is the new behavior (if this is a feature change)?**

No warning messages produced on KeyboardInterrupt

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

no

2020-05-15 21:25 UTC, A-Trash-Coder commented
This would be great. The message gets annoying.

2020-05-24 12:08 UTC, jianyuan commented
It doesn't work if we launch the task using `await bot.start()`. If used this way, we need to call `await self._websocket.close()`.

```python
def main():
	bot = Bot(...)
	await bot.start()

asyncio.run(main())
```

Raises:
```python
raise RuntimeError('This event loop is already running')
```

2021-01-29 23:12 UTC, IAmTomahawkx commented on twitchio/websocket.py
> +        self.loop.run_until_complete(self.loop.create_task(self._websocket.close()))
This won't work if the loop is running.

2021-01-29 23:13 UTC, IAmTomahawkx requested changes

2021-01-29 23:13 UTC, IAmTomahawkx commented on twitchio/websocket.py
> +        self.loop.run_until_complete(self.loop.create_task(self._websocket.close()))
This won't work if the loop is still running

2021-02-01 06:21 UTC, enykeev commented
I will not be returning to this PR after a year. Feel free to take over or close.

2021-02-01 06:31 UTC, closed without merging

2021-02-01 07:25 UTC, EvieePy commented
Sorry we haven't looked at this it's been a very busy time for me. This has actually been fixed in 2.0 aswell. Thanks for the PR.